name: dev_doctor
description: A free, opensource, serverless learning platform. A linwood project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: '1.5.2+14'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  enum_to_string: ^2.0.1
  http: ^0.13.3
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  flutter_modular: ^3.2.2+1
  url_launcher: ^6.0.4
  flutter_markdown: ^0.6.2
  #universal_html: ^1.2.4
  flutter_svg: ^0.22.0
  flutter_inappwebview: ^5.3.2
  xml: ^5.1.1
  flutter_localized_locales: ^2.0.2
  bitsdojo_window: ^0.1.0+1
  share_plus: ^2.1.2
  phosphor_flutter: ^1.2.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2
  yaml: ^3.1.0
  package_info_plus: ^1.0.1
  animations: ^2.0.0
  pdf: ^3.3.0
  printing: ^5.2.1
  flash: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
dev_dependencies:
  build_runner: ^2.0.4
  hive_generator: ^1.1.0
  msix: ^2.1.2
  flutter_test:
    sdk: flutter
  #integration_test:
  #  sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
          style: italic

        - asset: fonts/Roboto-Thin.ttf
          weight: 100
        - asset: fonts/Roboto-ThinItalic.ttf
          style: italic
          weight: 100

        - asset: fonts/Roboto-Light.ttf
          weight: 300
        - asset: fonts/Roboto-LightItalic.ttf
          style: italic
          weight: 300

        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: fonts/Roboto-Black.ttf
          weight: 900
        - asset: fonts/Roboto-BlackItalic.ttf
          style: italic
          weight: 900
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic

        - asset: fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
          
        - asset: fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
          style: italic
          weight: 300

        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600

        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800

        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic

        - asset: fonts/Raleway-Thin.ttf
          weight: 100
        - asset: fonts/Raleway-ThinItalic.ttf
          style: italic
          weight: 100
          
        - asset: fonts/Raleway-ExtraLight.ttf
          weight: 200
        - asset: fonts/Raleway-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-LightItalic.ttf
          style: italic
          weight: 300

        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
        - asset: fonts/Raleway-SemiBoldItalic.ttf
          style: italic
          weight: 600

        - asset: fonts/Raleway-Bold.ttf
          weight: 700
        - asset: fonts/Raleway-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: fonts/Raleway-ExtraBoldItalic.ttf
          style: italic
          weight: 800

        - asset: fonts/Raleway-Black.ttf
          weight: 900
        - asset: fonts/Raleway-BlackItalic.ttf
          style: italic
          weight: 900
    - family: 'Roboto Mono'
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Italic.ttf
          style: italic

        - asset: fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: fonts/RobotoMono-ThinItalic.ttf
          style: italic
          weight: 100
          
        - asset: fonts/RobotoMono-ExtraLight.ttf
          weight: 200
        - asset: fonts/RobotoMono-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: fonts/RobotoMono-LightItalic.ttf
          style: italic
          weight: 300

        - asset: fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoMono-SemiBoldItalic.ttf
          style: italic
          weight: 600

        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: fonts/RobotoMono-BoldItalic.ttf
          style: italic
          weight: 700
    - family: 'Comfortaa'
      fonts:
        - asset: fonts/Comfortaa-Regular.ttf

        - asset: fonts/Comfortaa-Light.ttf
          weight: 300

        - asset: fonts/Comfortaa-Medium.ttf
          weight: 500

        - asset: fonts/Comfortaa-SemiBold.ttf
          weight: 600

        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
    - family: 'Josefin Sans'
      fonts:
        - asset: fonts/JosefinSans-Regular.ttf
        - asset: fonts/JosefinSans-Italic.ttf
          style: italic

        - asset: fonts/JosefinSans-Thin.ttf
          weight: 100
        - asset: fonts/JosefinSans-ThinItalic.ttf
          style: italic
          weight: 100
          
        - asset: fonts/JosefinSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/JosefinSans-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: fonts/JosefinSans-Light.ttf
          weight: 300
        - asset: fonts/JosefinSans-LightItalic.ttf
          style: italic
          weight: 300

        - asset: fonts/JosefinSans-Medium.ttf
          weight: 500
        - asset: fonts/JosefinSans-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: fonts/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: fonts/JosefinSans-SemiBoldItalic.ttf
          style: italic
          weight: 600

        - asset: fonts/JosefinSans-Bold.ttf
          weight: 700
        - asset: fonts/JosefinSans-BoldItalic.ttf
          style: italic
          weight: 700
    - family: 'Oswald'
      fonts:
        - asset: fonts/Oswald-Regular.ttf
          
        - asset: fonts/Oswald-ExtraLight.ttf
          weight: 200

        - asset: fonts/Oswald-Light.ttf
          weight: 300

        - asset: fonts/Oswald-Medium.ttf
          weight: 500

        - asset: fonts/Oswald-SemiBold.ttf
          weight: 600

        - asset: fonts/Oswald-Bold.ttf
          weight: 700
    - family: 'Shippori Mincho'
      fonts:
        - asset: fonts/ShipporiMincho-Regular.ttf

        - asset: fonts/ShipporiMincho-Medium.ttf
          weight: 500

        - asset: fonts/ShipporiMincho-SemiBold.ttf
          weight: 600

        - asset: fonts/ShipporiMincho-Bold.ttf
          weight: 700

        - asset: fonts/ShipporiMincho-ExtraBold.ttf
          weight: 800
  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - translations/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
msix_config:
  display_name: Dev-Doctor
  publisher_display_name: Linwood
  identity_name: com.github.linwoodcloud.dev-doctor
  publisher: E=admin@linwood.tk, CN=CodeDoctorDE, OU=Linwood, O=Linwood, L=Dormagen, S=Nordrhein-Westfalen, C=DE
  msix_version: 1.5.2.0
  logo_path: images/logo.png
  start_menu_icon_path: images/logo.png
  tile_icon_path: images/logo.png
  #vs_generated_images_folder_path: build/windows/runner/Release/data/flutter_assets/images
  icons_background_color: '#ffffff'
  architecture: x64
  capabilities: 'internetClient,location,microphone,webcam'
