name: Flutter build

on: push

jobs:
  apk:
    runs-on: ubuntu-latest
    steps:
    - name: ⬆️ Checkout
      uses: actions/checkout@v1
    - name: 🔧 Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # or: 'stable' or 'dev'
    - name: ✅ Enable platforms
      run: flutter config --enable-web
    - name: 📦 Get dependencies
      run: flutter pub get
    #- run: flutter test
    - name: 🏭 Build
      run: |
        flutter build apk
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: apk-build
        path: build/app/outputs/flutter-apk/app-release.apk
  windows:
    runs-on: windows-latest
    steps:
    - name: ⬆️ Checkout
      uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # or: 'stable' or 'dev'
    - name: ✅ Enable platforms
      run: flutter config --enable-windows-desktop
    - name: 📦 Get dependencies
      run: flutter pub get
    - name: 🏭 Build
      run: |
        flutter build windows
        flutter pub run msix:create
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: |
           build/windows/runner/Release/**
  deploy:
    runs-on: ubuntu-latest
    needs:
    - apk
    - windows
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: apk-build
    - uses: actions/download-artifact@v2
      with:
        name: windows-build
        path: windows-build/
    - name: 🚀 Deploy release
      uses: eine/tip@master
      if: github.ref == 'refs/heads/main'
      with:
        tag: release
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          app-release.apk
          windows-build.zip
    - name: 📦 Zip artifacts
      run: |
        zip -j -r windows.zip windows-build/*
    - name: 🚀 Deploy preview
      uses: eine/tip@master
      if: github.ref == 'refs/heads/develop'
      with:
        tag: preview
        token: ${{ secrets.GITHUB_TOKEN }}
        rm: true
        files: |
          app-release.apk
          windows.zip