name: Flutter build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ⬆️ Checkout
      uses: actions/checkout@v1
    - name: 🔧 Setup java
      uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # or: 'stable' or 'dev'
    - name: ✅ Enable platforms
      run: flutter config --enable-web
    - name: 📦 Get dependencies
      run: flutter pub get
    #- run: flutter test
    - name: 🏭 Build
      run: |
        flutter build apk
    - name: Archive apk
      uses: actions/upload-artifact@v2
      with:
        name: apk-build
        path: output/test/code-coverage.html
    - name: 🚀 Deploy
      uses: eine/tip@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ GITHUB_REF#refs/heads/ }}
        files: |