name: Release

on:
  workflow_dispatch:
    inputs:
      next_version:
        default: "0.0.0"
        description: "The next version to be released"
        required: false
      stable:
        default: false
        description: "Is this version stable?"
        type: boolean
        required: false

jobs:
  release:
    runs-on: ubuntu-22.04
    outputs:
      build_number: ${{ steps.setup.outputs.build_number }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_PAT }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: "stable" # or: 'beta' or 'dev'
      - name: Setup git
        id: setup
        shell: bash
        run: |
          DEV-DOCTOR_VERSION_REGEX="version:\s(.+)\+(.+)"
          [[ $(grep -E "${DEV-DOCTOR_VERSION_REGEX}" app/pubspec.yaml) =~ ${DEV-DOCTOR_VERSION_REGEX} ]]
          DEV-DOCTOR_VERSION="${BASH_REMATCH[1]}"
          echo "DEV-DOCTOR_VERSION=${DEV-DOCTOR_VERSION}" >> $GITHUB_ENV
          DEV-DOCTOR_BUILD_NUMBER="${BASH_REMATCH[2]}"
          echo "DEV-DOCTOR_BUILD_NUMBER=${DEV-DOCTOR_BUILD_NUMBER}" >> $GITHUB_ENV
          echo "::set-output name=build_number::${DEV-DOCTOR_BUILD_NUMBER}"
          git config --global user.email "ci@linwood.dev"
          git config --global user.name "Linwood CI"
      - name: Create tag
        run: |
          DEV-DOCTOR_VERSION="${{ env.DEV-DOCTOR_VERSION }}"
          git tag -fa v${{ env.DEV-DOCTOR_VERSION }} -m "Release ${DEV-DOCTOR_VERSION}"
          git push origin v${DEV-DOCTOR_VERSION}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ github.event.inputs.stable != 'true' }}
          tag_name: v${{ env.DEV-DOCTOR_VERSION }}
          name: v${{ env.DEV-DOCTOR_VERSION }}
          token: ${{ secrets.CI_PAT }}
          body_path: fastlane/metadata/android/en-US/changelogs/${{ env.DEV-DOCTOR_BUILD_NUMBER }}.txt
      - name: Retag stable
        if: ${{ github.event.inputs.stable == 'true' || github.ref == 'refs/heads/main' }}
        run: |
          git tag -fa stable -m "Find all stable releases here"
          git push origin stable -f
      - name: Retag nightly
        if: ${{ github.event.inputs.stable != 'true' && github.ref == 'refs/heads/develop' }}
        run: |
          git tag -fa nightly -m "Find all nightly releases here"
          git push origin nightly -f
  update-version:
    runs-on: ubuntu-22.04
    needs:
      - release
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_PAT }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: "stable" # or: 'beta' or 'dev'
      - name: Setup git
        id: setup
        run: |
          DEV-DOCTOR_VERSION_REGEX="version:\s(.+)\+(.+)"
          [[ $(grep -E "${DEV-DOCTOR_VERSION_REGEX}" app/pubspec.yaml) =~ ${DEV-DOCTOR_VERSION_REGEX} ]]
          DEV-DOCTOR_VERSION="${BASH_REMATCH[1]}"
          echo "DEV-DOCTOR_VERSION=${DEV-DOCTOR_VERSION}" >> $GITHUB_ENV
          DEV-DOCTOR_BUILD_NUMBER="${BASH_REMATCH[2]}"
          echo "DEV-DOCTOR_BUILD_NUMBER=${DEV-DOCTOR_BUILD_NUMBER}" >> $GITHUB_ENV
          git config --global user.email "ci@linwood.dev"
          git config --global user.name "Linwood CI"
      - name: Set next version
        if:  ${{ github.event.inputs.stable != 'true' || github.ref != 'refs/heads/develop' }}
        run: |
          git fetch
          git pull origin
          dart pub get -C tools
          dart run tools/set_version.dart --build-number increment ${{ github.event.inputs.next_version }} --no-changelog
          git add .
          git commit -m "Update Version to ${{ github.event.inputs.next_version }}"
          git push origin
  update-main:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-22.04
    needs:
      - release
      - update-version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
          token: ${{ secrets.CI_PAT }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: "stable" # or: 'beta' or 'dev'
      - name: Setup git
        id: setup
        run: |
          git config --global user.email "ci@linwood.dev"
          git config --global user.name "Linwood CI"
      - name: Merge develop in main
        if:  ${{ github.event.inputs.stable == 'true' && github.ref == 'refs/heads/develop' }}
        run: |
          git fetch
          git pull
          git checkout main
          git pull
          git merge origin/develop --strategy-option ours
          git push origin main
      - name: Update version number
        if: ${{ github.event.inputs.stable != 'true' }}
        run: |
          dart pub get -C tools
          NEXT_BUILD_NUMBER=$(expr ${{ needs.release.outputs.build_number }} + 1)
          dart run tools/set_version.dart --build-number $NEXT_BUILD_NUMBER --no-changelog

          git add .
          git commit -m "Update version number"
          git push origin main
      - name: Merge main in develop
        run: |
          git fetch
          git pull
          git checkout develop
          git pull
          git merge origin/main --strategy-option ours
          git push origin develop
  update-develop:
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - release
      - update-version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.CI_PAT }}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: "stable" # or: 'beta' or 'dev'
      - name: Setup git
        id: setup
        run: |
          DEV-DOCTOR_VERSION_REGEX="version:\s(.+)\+(.+)"
          [[ $(grep -E "${DEV-DOCTOR_VERSION_REGEX}" app/pubspec.yaml) =~ ${DEV-DOCTOR_VERSION_REGEX} ]]
          DEV-DOCTOR_VERSION="${BASH_REMATCH[1]}"
          echo "DEV-DOCTOR_VERSION=${DEV-DOCTOR_VERSION}" >> $GITHUB_ENV
          DEV-DOCTOR_BUILD_NUMBER="${BASH_REMATCH[2]}"
          echo "DEV-DOCTOR_BUILD_NUMBER=${DEV-DOCTOR_BUILD_NUMBER}" >> $GITHUB_ENV
          git config --global user.email "ci@linwood.dev"
          git config --global user.name "Linwood CI"
      - name: Create changelog
        run: |
          dart pub get -C tools
          dart run tools/set_version.dart --build-number keep --changelog
          git add .
          git commit -m "Create changelog for ${{ env.DEV-DOCTOR_VERSION }}"
          git push origin
      - name: Merge main
        run: |
          git fetch
          git pull
          git checkout develop
          git pull
          git merge origin/main --strategy-option ours
          git push origin develop
      - name: Update version number
        run: |
          git fetch
          git pull
          dart pub get -C tools
          dart run tools/set_version.dart --build-number increment --no-changelog

          git add .
          git commit -m "Update version number"
          git push origin develop
  set-next-version:
    runs-on: ubuntu-22.04
    if:  ${{ github.event.inputs.stable == 'true' && github.ref == 'refs/heads/develop' }}
    needs:
      - release
      - update-version
      - update-main
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: develop
          token: ${{ secrets.CI_PAT }}
      - name: Setup
        id: setup
        run: |
          git config --global user.email "ci@linwood.dev"
          git config --global user.name "Linwood CI"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.2'
          channel: "stable" # or: 'beta' or 'dev'
      - name: Set next version
        run: |
          git fetch
          git pull origin
          dart pub get -C tools
          dart run tools/set_version.dart --build-number increment ${{ github.event.inputs.next_version }} --no-changelog
          git add .
          git commit -m "Update Version to ${{ github.event.inputs.next_version }}"
          git push origin
  notify:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_PAT }}
      - name: Get information
        shell: bash
        run: |
          DEV-DOCTOR_VERSION_REGEX="version:\s(.+)\+(.+)"
          [[ $(grep -E "${DEV-DOCTOR_VERSION_REGEX}" app/pubspec.yaml) =~ ${DEV-DOCTOR_VERSION_REGEX} ]]
          DEV-DOCTOR_VERSION="${BASH_REMATCH[1]}"
          echo "DEV-DOCTOR_VERSION=${DEV-DOCTOR_VERSION}" >> $GITHUB_ENV
          DEV-DOCTOR_BUILD_NUMBER="${BASH_REMATCH[2]}"
          echo "DEV-DOCTOR_BUILD_NUMBER=${DEV-DOCTOR_BUILD_NUMBER}" >> $GITHUB_ENV
          echo 'DEV-DOCTOR_CHANGELOG<<EOF' >> $GITHUB_ENV
          cat fastlane/metadata/android/en-US/changelogs/${DEV-DOCTOR_BUILD_NUMBER}.txt >> $GITHUB_ENV
          echo '' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        if: ${{ github.event.inputs.stable == 'true' || github.ref == 'refs/heads/main' }}
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: ${{ env.DEV-DOCTOR_VERSION }}
          embed-description: ${{ env.DEV-DOCTOR_CHANGELOG }}
          content: |
            Version ${{ env.DEV-DOCTOR_VERSION }} released!
            Download it here: https://docs.DEV-DOCTOR.linwood.dev/downloads

            https://github.com/LinwoodCloud/DEV-DOCTOR/releases/tag/v${{ env.DEV-DOCTOR_VERSION }}
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v4.0.0
        if: ${{ github.event.inputs.stable == 'false' && github.ref == 'refs/heads/develop' }}
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          embed-title: ${{ env.DEV-DOCTOR_VERSION }}
          embed-description: ${{ env.DEV-DOCTOR_CHANGELOG }}
          content: |
            Pre-release version ${{ env.DEV-DOCTOR_VERSION }} released!
            Download it here: https://docs.dev-doctor.linwood.dev/downloads

            Please note that this is a pre-release version and is not intended for production use.
            Read more about here: https://docs.dev-doctor.linwood.dev/nightly

  #publish-to-play-store:
  #  runs-on: ubuntu-22.04
  #  steps:
  #    - uses: actions/checkout@v3
  #    - name: Publish beta
  #      run: fastlane beta
  #      if: ${{ github.event.inputs.stable }}
  #      env:
  #        PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}
  #    - name: Publish stable
  #      run: fastlane deploy
  #      if: ${{ !github.event.inputs.stable }}
  #      env:
  #        PLAY_STORE_UPLOAD_KEY: ${{ secrets.PLAY_STORE_UPLOAD_KEY }}